// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tniakvynlwrsjpjhpque.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRuaWFrdnlubHdyc2pwamhwcXVlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUwNjExNjAsImV4cCI6MjA2MDYzNzE2MH0.h2RdCony_ze8BZoRx12F0QMfzaxdw2RMcQEKXB8TnQQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);